### ISSUE TITLE
Can't update to latest main

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/template-app-nuxt#11]
I just tried to update to the latest commit on`main` but can't – it looks like a rebased version of a previously published commit was pushed to the repo, which is the _one_ thing that should never be done when working collaboratively with Git.

I don't have time to work through the myriad of merge conflicts to get this solved, so would ask for the original commit to be force-pushed to restore the repo to its previous state and for the newest updates to simply be recorded with a regular new commit.

I'm aware this requires "breaking" the repo again, but considering the commit in question was last updated less than 2 hours ago, it's the far better choice. For reference: the original author date was 2023-07-15, i.e. a _month_ ago.

**Comment by stefanprobst** [comment]
i have force-pushed the original commit.

that said, this template is still not official. there are zero guarantees. i would advise against rebasing existing projects on top of it.

**Comment by koeaw** [comment]
> i have force-pushed the original commit.

Thank you.
 
> that said, this template is still not official. there are zero guarantees. i would advise against rebasing existing projects on top of it.

The repo for my project has a different root, but seeing as I have to work with this "zero guarantees" code base, I absolutely need to keep track of what's happening in here. Things that don't work in the template also don't work in my project, anything that's still a work in progress in the template is a WIP also in my project.

To understand changes or how to transfer/apply them to my project, I have to be able to follow and refer back to this repo's history. (Anything I try out in place builds on the same history.)
