### ISSUE TITLE
Remove RouteAnnouncer in favor of NuxtRouteAnnouncer

### ISSUE THREAD

**Issue by kkukelka** [acdh-oeaw/template-app-nuxt#19]
I believe Nuxt's built-in [NuxtRouteAnnouncer component](https://nuxt.com/docs/api/components/nuxt-route-announcer) should essentially accomplish the same thing as the current  `route-announcer.vue` component. To avoid the overhead I'd suggest to replace it. I can open a PR if you want.

**Comment by stefanprobst** [comment]
i think this was completed already in https://github.com/acdh-oeaw/template-app-nuxt/commit/e489568fcd49ab807dcdf1f95215e4acd7ac766c and https://github.com/acdh-oeaw/template-app-nuxt/commit/9be8ed824f1f7414514ffea75612e794b2601f6e - anything missing?

**Comment by kkukelka** [comment]
oh sorry, seems like i haven't pulled in a while 😅
