### ISSUE TITLE
Move TODOs to issues

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/template-app-nuxt#2]
I would suggest to move the contents of the [TODO file](https://github.com/acdh-oeaw/template-app-nuxt/blob/main/TODO.md) file to GitHub issues and to delete the file, but don't know what the plan is re: management of the code base/repo.

**Comment by stefanprobst** [comment]
agreed :+1:

currently, this is not official yet - there will be a contributing guide once we have a release.

**Comment by koeaw** [comment]
> currently, this is not official yet - there will be a contributing guide once we have a release.

If the template is actually still considered to be "under development", it might make sense to convert the current `main` branch into a `dev` branch and later start a new `main` branch off clean (ideally with an empty initial commit + any "messy" commits merged down).

I'm actually having this problem now that my version of the code over on GitLab starts out with a different root commit, so I can't cleanly combine the two repos as planned. :grimacing:
